name: CrcBiomeScreen
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.3.3
  - r-devtools
  - r-dplyr
  - r-ggplot2=3.5.2
  - r-mass=7.3_60.0.1
  - r-matrix=1.6_5
  - r-mgcv=1.9_1
  - r-ranger=0.17.0
  - r-foreach
  - r-doparallel
  - r-proc=1.18.5
  - r-tibble
  - r-tidyr
  - r-progress
  - r-progressr
  - r-future
  - r-future.apply
  - r-ape
  - r-caret
  - r-vegan
  - r-xgboost=1.7
  - r-ggpubr
  - r-ggrepel
  - r-ggplotify
  - r-biocmanager
  - bioconductor-curatedmetagenomicdata
  - bioconductor-microbiomemarker
  - r-gunifrac
