name: CrcBiomeScreen
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.3
  - r-devtools
  - r-ggplot2>=3.5.2
  - r-matrix>=1.6_5
  - r-mass>=7.3_60.0.1
  - r-mgcv>=1.9_1
  - r-caret
  - bioconductor-curatedmetagenomicdata
  - bioconductor-phyloseq
  - r-ranger
  - r-xgboost
  - r-foreach
  - r-doparallel
  - r-progress
  - r-pROC
