name: CrcBiomeScreen
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.3.3
  - r-devtools
  - r-dplyr
  - r-ggplot2=3.5.2
  - r-mass=7.3_60.0.1
  - r-matrix=1.6_5
  - r-mgcv=1.9_1
  - r-ranger
  - r-foreach
  - r-doParallel
  - r-pROC
  - r-tibble
  - r-tidyr
  - r-progress
  - r-progressr
  - r-future
  - r-future.apply
  - r-ape
  - r-caret
  - r-vegan
  - r-xgboost
  - r-ggpubr
  - r-ggrepel
  - r-ggplotify
